### ISSUE TITLE
Please adjust width of table

### ISSUE THREAD

**Issue by KeiroKamioka0000** [mspnp/architecture-center.ja-jp#32]
https://docs.microsoft.com/ja-jp/azure/architecture/best-practices/naming-conventions#naming-rules-and-restrictions

As you may notice, please consider to edit the width of table,
It really hard to read.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 0e540bb6-9f72-0529-28ea-ae82bc869835
* Version Independent ID: 24e71392-985b-59fb-1552-46395b169612
* Content: [Azure リソースの名前付け規則 - Best practices for cloud applications](https://docs.microsoft.com/ja-jp/azure/architecture/best-practices/naming-conventions#naming-rules-and-restrictions)
* Content Source: [docs/best-practices/naming-conventions.md](https://github.com/mspnp/architecture-center.ja-jp/blob/live/docs/best-practices/naming-conventions.md)
* Service: **architecture-center**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by CeciAc** [comment]
Hello, @KeiroKamioka0000 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi Isha
I'm assigning this one to you since is out of our scope.

Kind regards,
Microsoft DOCS International Team

**Comment by ishasahni1** [comment]
@CeciAc 

Please open a source issue or PR, for this topic writer, as they can help in addressing this issue.

**Comment by KeiroKamioka0000** [comment]
I think I verify the fix for this document.
I assuming it fixed with similar post I made in another document.

**Comment by CeciAc** [comment]
Issue moved to [mspnp/architecture-center #1343](https://github.com/mspnp/architecture-center/issues/1343) via [**ZenHub**](https://www.zenhub.com/)
